# Generated by Django 2.2.16 on 2022-02-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220215_2323'),
        ('reviews', '0005_auto_20220215_2255'),
    ]

    operations = [
    ]
