# Generated by Django 2.2.16 on 2022-02-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220203_1935'),
        ('reviews', '0007_auto_20220203_1840'),
    ]

    operations = [
    ]
