# Generated by Django 2.2.16 on 2022-02-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220203_1840'),
        ('reviews', '0007_auto_20220206_2110'),
    ]

    operations = [
    ]
