# Generated by Django 2.2.16 on 2022-02-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220207_2233'),
        ('reviews', '0008_merge_20220207_1922'),
    ]

    operations = [
    ]
